name: Publish to Github Packages

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Publish Maven Package
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Publish
        run: mvn --batch-mode deploy
        env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
